import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>New World Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/capital">My Application!</a>
        </h1>
        <br />

        <h2>What would you like to find out?</h2>
        <br />
        <div>
          <h3 className={styles.category}>Categories</h3>
          <div>
            <ul className={styles.list}>
              <li className={styles.card} >
                <Link href="/capital">Find the Capital...</Link>
              </li>
              <li className={styles.card}>
                <Link href="/regionLanguages">Languages spoken in a region...</Link>
              </li>
              <li className={styles.card}>
                <Link href="/cityWithLang">Count of cities where a certain language is spoken...</Link>
              </li>
              <li className={styles.card}>
                <Link href="/countLangPerCont">Continents and the the number of languages spoken in each</Link>
              </li>
              <li className={styles.card}>
                <Link href="/country">Any country(s) that has the same official language and continent as the country you entered.</Link>
              </li>
            </ul>
          </div>
        </div>


        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
